services:
  - type: web
    name: axiom-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_API_KEY_2
        sync: false
      - key: GROQ_API_KEY_3
        sync: false
      - key: GROQ_API_KEY_4
        sync: false
      - key: GROQ_API_KEY_5
        sync: false
      - key: FINNHUB_KEY
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_WEB_API_KEY
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: VAPID_EMAIL
        sync: false
      - key: CLIENT_URL
        sync: false
